### ISSUE TITLE
broken link in readme for prettier package

### ISSUE THREAD

**Issue by jasikpark** [un-ts/toml-tools#39]
https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml/test-packages/test-prettier-plugin-toml -> https://github.com/bd82/toml-tools/tree/master/test-packages/test-prettier-plugin-toml

currently the link is written as `../../test-packages/test-prettier-plugin-toml`

**Comment by bd82** [comment]
Thanks for reporting this @jasikpark 

However I will likely officially deprecate this package soon as I do not have time to maintain it so I won't fix it 😢 

Cheers.

**Comment by jasikpark** [comment]
Ok, thanks for the info - I wish I could figure out how to integrate https://taplo.tamasfe.dev/ with prettier for toml? If this is going to be deprecated.

**Comment by jasikpark** [comment]
https://taplo.tamasfe.dev/lib/#features-2 hmm maybe this could be integrated so that maintenance is not as extensive? I guess I might look into it

**Comment by bd82** [comment]
maintenance is not expensive at all.
I just:
1. Have no personal use for this project.
2. Have less time for OSS nowadays and want to focus on 1/2 projects only in OSS context.
