### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by bd82** [un-ts/toml-tools#43]
I no longer have time to maintain this project.
If anyone is interested in taking over this project please reply in this thread.

**Comment by aminya** [comment]
I can publish the package on npm if that is the issue.

**Comment by JounQin** [comment]
@bd82 Hi, I'd like to help here, I'm also maintaining some prettier plugins at https://github.com/un-ts/prettie.

**Comment by bd82** [comment]
And do you want to move this code into your mono-repo in https://github.com/un-ts/prettier?
or keep it as a  separate repo?

**Comment by JounQin** [comment]
@bd82 Thanks for reply.

I'd prefer to keep the npm package name if permitted.

For the repo, I'd like to keep it separate for now and would you mind to transfer it to a new organization like @un-ts? That would make permissions transfer easier I think.

For the npm package, I can be easily done by `npm owner add <username>` command, see also https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account if you prefer web UI. My npm account is `@jounqin`.

**Comment by bd82** [comment]
It seems I need permissions to create new repos on `un-ts` for the transfer to be initiated



![image](https://github.com/bd82/toml-tools/assets/4233843/07ff71e4-2d1d-4c7b-b64d-876928aed262)

**Comment by bd82** [comment]
@JounQin I invited you as a maintainer for `prettier-plugin-toml` package on npmjs.com

**Comment by bd82** [comment]
And I also invited you as collaborator on this repo.
But I do not think this will suffice to make the transfer.

I suspect I will need **temporary** create repo permissions on `un-ts` to perform the transfer

**Comment by JounQin** [comment]
@bd82 I've invited you to @un-ts.

**Comment by bd82** [comment]
I am not seeing any invite, perhaps it timed out.
Anyhow I moved the repo to a new **temp** org (toml-tools-temp) and sent you an invite
for OWNER permissions on this new org.

Once you move the repo to your org, I will delete this temp org...

**Comment by JounQin** [comment]
Thanks @bd82 ! I've transferred the repository and deleted the temp organization.

**Comment by JounQin** [comment]
Hi, @bd82 do you have time to change my role on npm org toml-tools?

<img width="1529" alt="image" src="https://github.com/un-ts/toml-tools/assets/8336744/60ea26cb-dfa5-4336-b868-9e761aeee7d8">
