### ISSUE TITLE
`prettier-plugin-toml` does not seem to work using the command line

### ISSUE THREAD

**Issue by David-Else** [un-ts/toml-tools#69]
```
npm ls -g
/usr/local/lib
├── prettier-plugin-toml@1.0.0
├── prettier@3.0.2
```
```
$ node --version
v18.13.0
$ npm --version
9.2.0
```

I have Prettier and `prettier-plugin-toml` installed globally.

I try:

```
prettier --write testconfig.toml
```
and get:
```
[error] No parser could be inferred for file "/home/david/Downloads/testconfig.toml".
```
I also try:
```
prettier --plugin=prettier-plugin-toml testconfig.toml
```
and get:
```
[error] Cannot find package 'prettier-plugin-toml' imported from /home/david/Downloads/noop.js
```
Am I missing something here, or is there a bug? Thanks.

**Comment by JounQin** [comment]
Maybe a prettier core bug?

**Comment by David-Else** [comment]
> Maybe a prettier core bug?

Seems unlikely, could you give an example of a command that you have used that definitely works?

**Comment by JounQin** [comment]
> Seems unlikely

How do you confirm this? I've never used global installed plugins. Did you tried any other plugin that works?

**Comment by bruceadams** [comment]
I see the same problem using `npx`. I cannot use the 1.0.0 release of `prettier-plugin-toml`. The 0.4.0 release works fine. (I'm using `npx` here outside of any JavaScript project.)

```
% npx --package=prettier-plugin-toml@1.0.0 prettier --tab-width 4 --write pyproject.toml
[error] No parser could be inferred for file "/Users/bruce/clo/triple-settlement-rewards-network/pyproject.toml".
% npx --package=prettier-plugin-toml@0.4.0 prettier --tab-width 4 --write pyproject.toml
pyproject.toml 7ms
```

**Comment by kassiansun** [comment]
> I see the same problem using `npx`. I cannot use the 1.0.0 release of `prettier-plugin-toml`. The 0.4.0 release works fine. (I'm using `npx` here outside of any JavaScript project.)
> 
> ```
> % npx --package=prettier-plugin-toml@1.0.0 prettier --tab-width 4 --write pyproject.toml
> [error] No parser could be inferred for file "/Users/bruce/clo/triple-settlement-rewards-network/pyproject.toml".
> % npx --package=prettier-plugin-toml@0.4.0 prettier --tab-width 4 --write pyproject.toml
> pyproject.toml 7ms
> ```

Thanks a lot for this reply, I finally find a way to run `prettier-plugin-toml` with npx and vim `autocmd`

**Comment by Tatsh** [comment]
Newest version of Prettier seems to need `plugins` set. Seems to no longer auto-load them. Either with `--plugin=NAME` or in configuration:

```json
 "plugins": ["prettier-plugin-ini", "prettier-plugin-toml"]
```

https://prettier.io/docs/en/plugins

**Comment by bruceadams** [comment]
@Tatsh Thanks for the pointer to the [Prettier documentation about plugins](https://prettier.io/docs/en/plugins)! Unfortunately, Prettier's `--plugin` option doesn't seem to work with `npx` 😢 

```
% npx --package=prettier-plugin-toml prettier --plugin=prettier-plugin-toml --tab-width 4 --write pyproject.toml
[error] Cannot find package 'prettier-plugin-toml' imported from /Users/bruce/sample-pythoni/noop.js
```

**Comment by bruceadams** [comment]
The workaround in [this comment on a Prettier issue](https://github.com/prettier/prettier/issues/15141#issuecomment-1669848678) works with `npx` 🎉.

```
% npx prettier-pnp --pn toml --tab-width 4 --write pyproject.toml

----- Already installed ----

 - prettier-plugin-toml

----- Running prettier -----

pyproject.toml 5ms
```

**Comment by Tatsh** [comment]
With a global install the full path to the main export must be given (`.exports['.']` in `package.json`):

```shell
prettier --plugin=${HOME}/somewhere/node_modules/prettier-plugin-toml/lib/api.js a.toml
```

This can be made easier by using a global config.

**Comment by JounQin** [comment]
So it's really a prettier core issue, I'll close this issue for now, if you still confirm it's related to this plugin instead, please raise a new issue with reproduction, thanks all.
