### ISSUE TITLE
Constantly crashes with "Cannot read properties of undefined (reading 'tokenTypeIdx')"

### ISSUE THREAD

**Issue by thewilkybarkid** [un-ts/toml-tools#70]
Adding `prettier-plugin-toml` to an existing project using Prettier 3 sees it constantly crash with `Cannot read properties of undefined (reading 'tokenTypeIdx')`. It seems to have when Prettier is processing any file (not just TOML files).

This seems to be as much debugging info as I can get:

```
$ prettier --ignore-unknown --check '**' --log-level debug

[debug] normalized argv: {"":["**"],"cache":false,"check":true,"color":true,"editorconfig":true,"ignoreUnknown":true,"logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":["**"],"__raw":{"_":["**"],"cache":false,"check":true,"color":true,"editorconfig":true,"ignore-unknown":true,"log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
Checking formatting...
[debug] resolve config from '[some-file-in-my-project]'
[debug] loaded options `[contents-of-my-.prettierrc-file]`
[error] Cannot read properties of undefined (reading 'tokenTypeIdx')
```

I've tried removing all my Prettier config, running it on a single TOML file, running it on a single non-TOML file etc., but it constantly crashes when the plugin is enabled (either in the config file or on the command line).

This might be the same problem as in https://github.com/un-ts/toml-tools/issues/42.

**Comment by JounQin** [comment]
What version are you using?

**Comment by JounQin** [comment]
Please try `prettier-plugin-toml@v2`

**Comment by thewilkybarkid** [comment]
It works now, thanks! (To confirm, I was using `^1.0.0` previously.)
