### ISSUE TITLE
Parsing error when double quoted string contains tab.

### ISSUE THREAD

**Issue by pnchen** [un-ts/toml-tools#73]
```
test = "	"
```
OR
```
test = """
	
"""
```

![image](https://github.com/un-ts/toml-tools/assets/2562679/8f128f6e-768d-452f-9f94-61ba6295a9ea)

**Comment by JounQin** [comment]
Thanks for raising this, I'll take a look when I'm free.

**Comment by JounQin** [comment]
Please try `prettier-plugin-toml@v2`
